name: Hexlet CI Fork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup
      run: make setup

    - name: tests
      run: make test

    - name: lint
      run: make lint
