name: Hexlet CI Fork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        
    - name: setup
      run: make setup

    - name: tests
      run: make test

    - name: lint
      run: make lint
      
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ SNYK_SECRET_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
